apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-dados
spec:
    accesModes:
      - ReadWriteOnce
    resources:
        requests:
            storage:10Gi
    storageClassName: standard-rwo  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mvcardim//projeto-database:1.0
        args:
            - "--ignore-db-dir=lost+found"
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        -name: mysql-dados
        persistentVolumeclaim:
            calaimName: mysql-dados


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: mvcardim/projeto-backend:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
